# Generated by Django 5.0.6 on 2024-09-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_remove_bank_policy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='operating_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankpolicy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
