# Generated by Django 5.0.6 on 2024-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_objectives', models.TextField(blank=True, null=True)),
                ('loan_requirements', models.TextField(blank=True, null=True)),
                ('loan_circumstances', models.TextField(blank=True, null=True)),
                ('loan_financial_awareness', models.TextField(blank=True, null=True)),
                ('loan_prioritised', models.TextField(blank=True, null=True)),
                ('lender_loan', models.TextField(blank=True, null=True)),
                ('loan_structure', models.TextField(blank=True, null=True)),
                ('goals_objectives', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
