# Generated by Django 5.0.6 on 2024-07-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_service', '0002_cashoutchoice_clientinterviewchoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cash_out_involved',
            field=models.CharField(blank=True, choices=[('assist_with_the_property_purchase_transaction', 'Assist with the property purchase transaction'), ('non_structural_renovation_of_existing_properties', 'Non-structural renovation of existing properties'), ('to_cash_buy_future_australian_property_outright', 'To cash buy future Australian property outright')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='client_interview_method',
            field=models.CharField(blank=True, choices=[('face_to_face', 'Face to Face'), ('video', 'Video'), ('telephone', 'Telephone'), ('email', 'Email')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='document_identification_method',
            field=models.CharField(blank=True, choices=[('face_to_face', 'Face to Face'), ('certified_persons', 'Certified Persons'), ('branch', 'Branch'), ('video_over_internet', 'Video over Internet')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='repayment_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('fortnightly', 'Fortnightly'), ('weekly', 'Weekly')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_2',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_1',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_3',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan_structure',
            field=models.CharField(blank=True, choices=[('standalone', 'Standalone'), ('cross_collateralised', 'Cross-Collateralised'), ('multiple_securities', 'Multiple Securities')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('fixed_rate', 'Fixed Rate'), ('variable_rate', 'Variable Rate'), ('fixed_and_variable_rate', 'Fixed & Variable Rate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='repayment_type',
            field=models.CharField(blank=True, choices=[('interest_only', 'Interest Only'), ('p_and_l_repayments', 'P&L Repayments')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CashOutChoice',
        ),
        migrations.DeleteModel(
            name='ClientInterviewChoice',
        ),
        migrations.DeleteModel(
            name='DocumentIdentificationChoice',
        ),
        migrations.DeleteModel(
            name='FrequencyChoice',
        ),
        migrations.DeleteModel(
            name='LenderChoice',
        ),
        migrations.DeleteModel(
            name='LoanStructureChoice',
        ),
        migrations.DeleteModel(
            name='RateChoice',
        ),
        migrations.DeleteModel(
            name='RepaymentChoice',
        ),
    ]
