# Generated by Django 5.0.6 on 2024-09-03 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_service', '0003_alter_note_cash_out_involved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(max_length=100)),
                ('prompt', models.TextField(choices=[('loan_objectives', 'Loan Objectives'), ('loan_requirements', 'Loan Requirements'), ('loan_circumstances', 'Loan Circumstances'), ('loan_financial_awareness', 'Loan Financial Awareness'), ('loan_prioritised', 'Loan Prioritised'), ('lender_loan', 'Lender Loan'), ('loan_structure', 'Loan Structure'), ('goals_objectives', 'Goals Objectives')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_prompt', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_prompt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
