# Generated by Django 5.0.6 on 2024-09-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_service', '0004_compliancesystemprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancesystemprompt',
            name='prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='compliancesystemprompt',
            name='prompt_type',
            field=models.CharField(choices=[('loan_objectives', 'Loan Objectives'), ('loan_requirements', 'Loan Requirements'), ('loan_circumstances', 'Loan Circumstances'), ('loan_financial_awareness', 'Loan Financial Awareness'), ('loan_prioritised', 'Loan Prioritised'), ('lender_loan', 'Lender Loan'), ('loan_structure', 'Loan Structure'), ('goals_objectives', 'Goals Objectives')]),
        ),
    ]
