# Generated by Django 5.0.6 on 2024-09-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_service', '0005_alter_compliancesystemprompt_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancesystemprompt',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
