# Generated by Django 5.0.6 on 2024-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_service', '0006_alter_compliancesystemprompt_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_1',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money'), ('bankwest', 'Bankwest'), ('ing', 'Ing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_2',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money'), ('bankwest', 'Bankwest'), ('ing', 'Ing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_3',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money'), ('bankwest', 'Bankwest'), ('ing', 'Ing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('fixed_rate', 'Fixed Rate'), ('variable_rate', 'Variable Rate'), ('fixed_and_variable_rate', 'Fixed & Variable Rate'), ('Variable', 'Variable'), ('Fixed', 'Fixed')], max_length=50, null=True),
        ),
    ]
