# Generated by Django 5.0.6 on 2024-11-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_service', '0007_alter_note_loan_scenario_lender_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_1',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money'), ('bankwest', 'Bankwest'), ('ing', 'Ing'), ('great_southern_bank', 'Great Southern Bank')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_2',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money'), ('bankwest', 'Bankwest'), ('ing', 'Ing'), ('great_southern_bank', 'Great Southern Bank')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='loan_scenario_lender_3',
            field=models.CharField(blank=True, choices=[('aaa_finance', 'AAA Finance'), ('anz_bank', 'ANZ Bank'), ('boq', 'BOQ'), ('cba', 'CBA'), ('heritage', 'Heritage'), ('st_george_bank', 'St. George Bank'), ('macquarie_bank', 'Macquarie Bank'), ('hsbc', 'HSBC'), ('nab', 'NAB'), ('suncorp', 'Suncorp'), ('westpac', 'Westpac'), ('bc_invest', 'BC Invest'), ('brighten', 'Brighten'), ('la_trobe', 'LaTrobe'), ('mezy', 'MEZY'), ('ma_money', 'MA Money'), ('bankwest', 'Bankwest'), ('ing', 'Ing'), ('great_southern_bank', 'Great Southern Bank')], max_length=100, null=True),
        ),
    ]
