# Generated by Django 5.0.6 on 2024-12-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_service', '0008_alter_note_loan_scenario_lender_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='note',
            name='goals_objectives_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='loan_features_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
