# Generated by Django 5.0.6 on 2024-09-04 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_service', '0002_note_notepdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerNoteSystemprompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('loan_purpose', 'Loan Purpose'), ('applicant_overview', 'Applicant Overview'), ('living_condition', 'Living Condition'), ('employment_income', 'Employment Income'), ('commitments', 'Commitments'), ('others', 'Others'), ('mitigants', 'Mitigants')])),
                ('prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broker_note_system_prompt', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_broker_note_system_prompt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
