# Generated by Django 5.0.6 on 2024-07-22 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('residency', models.CharField(blank=True, max_length=99, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('purchase', 'PURCHASE'), ('refinance', 'REFINANCE')], max_length=20)),
                ('website_tracking_id', models.CharField(max_length=255, null=True, unique=True)),
                ('json_data', models.JSONField(default=dict)),
                ('api_request', models.JSONField(default=dict)),
                ('api_response', models.JSONField(default=dict)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunity_services', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_opportunity_services', to=settings.AUTH_USER_MODEL)),
                ('secondary_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_contact_opportunity_services', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_opportunity_services', to=settings.AUTH_USER_MODEL)),
                ('user_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_opportunity_services', to='opportunity_app.contactsopportunity')),
            ],
        ),
    ]
