# Generated by Django 5.0.6 on 2024-07-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('engaged', 'Engaged'), ('success', 'Success'), ('unsuccessful', 'Unsuccessful'), ('ideal', 'Ideal')], default='engaged', max_length=20),
        ),
    ]
