# Generated by Django 5.0.6 on 2024-07-24 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='api_request',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='api_response',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='secondary_contact',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='user_contact',
        ),
        migrations.AddField(
            model_name='contactsopportunity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='applicant_contacts',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='opportunity_app.contactsopportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='primary_processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_processor_opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='secondary_contacts',
            field=models.ManyToManyField(blank=True, related_name='secondary_opportunities', to='opportunity_app.contactsopportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='secondary_processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_processor_opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactsopportunity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactsopportunity',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='primary_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_opportunities', to='opportunity_app.contactsopportunity'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('refinance', 'Refinance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_opportunity', to=settings.AUTH_USER_MODEL),
        ),
    ]
