# Generated by Django 5.0.6 on 2024-07-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0002_remove_opportunity_api_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='applicant_contacts',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='secondary_contacts',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='other_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_opportunities', to='opportunity_app.contactsopportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='secondary_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_opportunities', to='opportunity_app.contactsopportunity'),
        ),
    ]
