# Generated by Django 5.0.6 on 2024-07-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0003_stage_alter_opportunity_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsopportunity',
            name='country_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
