# Generated by Django 5.0.6 on 2024-07-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0004_contactsopportunity_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsopportunity',
            name='website_date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsopportunity',
            name='website_feild_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactsopportunity',
            name='website_form_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
