# Generated by Django 5.0.6 on 2024-07-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0005_contactsopportunity_website_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsopportunity',
            old_name='website_feild_id',
            new_name='website_field_id',
        ),
    ]
