# Generated by Django 5.0.6 on 2024-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0006_rename_website_feild_id_contactsopportunity_website_field_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsopportunity',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
