# Generated by Django 5.0.6 on 2024-07-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0007_alter_contactsopportunity_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsopportunity',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
