# Generated by Django 5.0.6 on 2024-11-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0009_contactsopportunity_citizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='other_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_opportunities', to='opportunity_app.contactsopportunity'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunity_app.stage'),
        ),
    ]
