# Generated by Django 5.0.6 on 2024-11-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_app', '0010_alter_opportunity_other_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='secondary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_opportunities', to='opportunity_app.contactsopportunity'),
        ),
    ]
